# Generated by Django 3.2.7 on 2023-02-07 14:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name=' Nombres ')),
                ('chapa', models.CharField(max_length=7, unique=True, verbose_name=' Chapas ')),
                ('cedula', models.CharField(max_length=7, unique=True, verbose_name=' Cedula ')),
            ],
            options={
                'verbose_name': 'Camion',
                'verbose_name_plural': 'Camions',
                'db_table': 'Camions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CateQuimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, null=True, verbose_name=' CategoriaQ ')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name=' Nombres ')),
                ('telefono', models.CharField(max_length=150, unique=True, verbose_name=' Telefonos ')),
                ('ruc', models.CharField(max_length=150, unique=True, verbose_name=' Ruc ')),
                ('email', models.CharField(max_length=150, unique=True, verbose_name=' email ')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name=' Nombres ')),
                ('ci', models.CharField(max_length=10, unique=True, verbose_name=' Ci ')),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Parcelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name=' Nombres ')),
                ('ubicacion', models.CharField(max_length=150, unique=True, verbose_name=' Ubicacion ')),
                ('hectareas', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gasto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'db_table': 'Parcelas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name=' Names ')),
                ('telefono', models.CharField(max_length=150, unique=True, verbose_name=' Telefonos ')),
                ('ruc', models.CharField(max_length=150, unique=True, verbose_name=' Ruc ')),
                ('email', models.CharField(max_length=150, unique=True, verbose_name=' email ')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='tipo_trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name=' Nombres ')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name=' Nombres ')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name=' Nombres ')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hectareas', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('descripcion', models.CharField(max_length=50, verbose_name=' descripcion ')),
                ('gasto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('parcela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.parcelas')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipo_trabajo')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
                'db_table': 'Trabajos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Quimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name=' Nombre ')),
                ('ingrediente', models.CharField(max_length=10, unique=True, verbose_name=' Descripcion ')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.catequimico')),
                ('procedencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
                ('unidades', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unidades')),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('parcela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.parcelas')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.quimico')),
            ],
            options={
                'verbose_name': 'Produccion',
                'verbose_name_plural': 'Producciones',
                'db_table': 'Produccion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Grano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name=' Nombres ')),
                ('variedad', models.CharField(max_length=10, verbose_name=' Variedad ')),
                ('stock', models.IntegerField(default=0)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('Procedencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
            ],
            options={
                'verbose_name': 'Semilla',
                'verbose_name_plural': 'Semillas',
                'db_table': 'Grano',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('camion_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.camion')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('grano_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.quimico')),
            ],
            options={
                'verbose_name': 'Entregas',
                'verbose_name_plural': 'Entregas',
                'db_table': 'Entregas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.type'),
        ),
        migrations.CreateModel(
            name='Det_Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('quimico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.quimico')),
                ('trabajo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.trabajo')),
            ],
            options={
                'verbose_name': 'Trabajo Detalle',
                'verbose_name_plural': 'Trabajo Detalle',
                'db_table': 'Trabajo Detalle',
                'ordering': ['id'],
            },
        ),
    ]
