# Generated by Django 3.2.7 on 2023-02-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_employee_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='names',
            new_name='name',
        ),
    ]
