# Generated by Django 3.2.7 on 2022-09-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220922_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name=' Nombres ')),
                ('variedad', models.CharField(max_length=10, unique=True, verbose_name=' Variedad ')),
                ('Kilogramos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Semilla',
                'verbose_name_plural': 'Semillas',
                'db_table': 'Grano',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
