# Generated by Django 4.1 on 2022-09-29 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220922_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name=' Nombres ')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'ordering': ['id'],
            },
        ),
        migrations.RenameField(
            model_name='grano',
            old_name='Kilogramos',
            new_name='kilogramos',
        ),
        migrations.CreateModel(
            name='Quimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name=' Nombres ')),
                ('variedad', models.CharField(max_length=10, unique=True, verbose_name=' Variedad ')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('unidades', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unidades')),
            ],
            options={
                'verbose_name': 'Quimico',
                'verbose_name_plural': 'Quimicos',
                'db_table': 'Quimicos',
                'ordering': ['id'],
            },
        ),
    ]
