# Generated by Django 4.1 on 2022-09-29 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_unidades_rename_kilogramos_grano_kilogramos_quimico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quimico',
            old_name='variedad',
            new_name='Ingrediente',
        ),
    ]
