# Generated by Django 3.2.7 on 2023-02-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_parcelas_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quimico',
            name='ingrediente',
            field=models.CharField(max_length=255, unique=True, verbose_name=' Descripcion '),
        ),
    ]
