# Generated by Django 3.2.7 on 2022-10-06 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_variedad_quimico_ingrediente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='names',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='unidades',
            old_name='names',
            new_name='name',
        ),
    ]
