# Generated by Django 3.2.7 on 2022-10-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221006_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='quimico',
            name='descripcion',
            field=models.CharField(default='no_description', max_length=150, verbose_name=' descripciones '),
        ),
    ]
