# Generated by Django 3.2.7 on 2022-10-25 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_quimico_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quimico',
            old_name='Ingrediente',
            new_name='ingrediente',
        ),
    ]
