# Generated by Django 3.2.7 on 2022-10-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_quimico_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateQuimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CateforiaQ', models.CharField(max_length=150, verbose_name=' CateforiaQ ')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
    ]
