# Generated by Django 3.2.7 on 2022-10-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_catequimico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catequimico',
            name='CateforiaQ',
        ),
        migrations.AddField(
            model_name='catequimico',
            name='CategoriaQ',
            field=models.CharField(default='no_description', max_length=150, verbose_name=' CategoriaQ '),
        ),
    ]
