# Generated by Django 3.2.7 on 2022-10-26 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20221025_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='quimico',
            name='Categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.catequimico'),
        ),
        migrations.AlterField(
            model_name='catequimico',
            name='CategoriaQ',
            field=models.CharField(default='no_description', max_length=150, null=True, verbose_name=' CategoriaQ '),
        ),
    ]
