# Generated by Django 3.2.7 on 2022-10-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20221025_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quimico',
            old_name='cantidad',
            new_name='gasto',
        ),
        migrations.RenameField(
            model_name='quimico',
            old_name='ingrediente',
            new_name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='quimico',
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='quimico',
            name='unidades',
        ),
        migrations.AddField(
            model_name='quimico',
            name='hectareas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quimico',
            name='trabajos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
