# Generated by Django 3.2.7 on 2022-10-27 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20221026_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name=' Nombres ')),
                ('ubicacion', models.CharField(max_length=10, unique=True, verbose_name=' Ubicacion ')),
                ('hectareas', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('trabajos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gasto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'db_table': 'Parcelas',
                'ordering': ['id'],
            },
        ),
        migrations.RenameField(
            model_name='quimico',
            old_name='gasto',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='quimico',
            old_name='ubicacion',
            new_name='ingrediente',
        ),
        migrations.RemoveField(
            model_name='quimico',
            name='hectareas',
        ),
        migrations.RemoveField(
            model_name='quimico',
            name='trabajos',
        ),
        migrations.AddField(
            model_name='quimico',
            name='Categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.catequimico'),
        ),
        migrations.AddField(
            model_name='quimico',
            name='unidades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.unidades'),
        ),
    ]
