# Generated by Django 3.2.7 on 2022-10-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20221026_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catequimico',
            name='CategoriaQ',
            field=models.CharField(max_length=150, null=True, verbose_name=' CategoriaQ '),
        ),
    ]
