# Generated by Django 3.2.7 on 2022-10-27 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_catequimico_categoriaq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catequimico',
            old_name='CategoriaQ',
            new_name='name',
        ),
    ]
