# Generated by Django 3.2.7 on 2022-10-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20221027_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='grano',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
