# Generated by Django 3.2.7 on 2022-10-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_grano_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catequimico',
            old_name='name',
            new_name='noobre',
        ),
        migrations.AlterField(
            model_name='grano',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='grano',
            name='procedencia',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name=' Procedencia '),
        ),
    ]
