# Generated by Django 3.2.7 on 2022-10-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20221027_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelas',
            name='ubicacion',
            field=models.CharField(max_length=150, unique=True, verbose_name=' Ubicacion '),
        ),
    ]
