# Generated by Django 3.2.7 on 2022-10-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_parcelas_ubicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catequimico',
            old_name='noobre',
            new_name='nombre',
        ),
    ]
