# Generated by Django 3.2.7 on 2022-12-21 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_noobre_catequimico_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_conductor', models.CharField(max_length=150, verbose_name=' Nombres ')),
                ('chapa', models.CharField(max_length=150, unique=True, verbose_name=' Chapas ')),
                ('cedula', models.CharField(max_length=150, unique=True, verbose_name=' cedula ')),
            ],
            options={
                'verbose_name': 'Camion',
                'verbose_name_plural': 'Camions',
                'db_table': 'Camions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='tipo_trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name=' Nombres ')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hectareas', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name=' descripcion ')),
                ('gasto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('parcela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.parcelas')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipo_trabajo')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
                'db_table': 'Trabajos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Trabajo_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gasto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('quimico_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.quimico')),
                ('trabajo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.trabajo')),
            ],
            options={
                'verbose_name': 'Trabajo Stock',
                'verbose_name_plural': 'Trabajo Stock',
                'db_table': 'Trabajo Stock',
                'ordering': ['id'],
            },
        ),
    ]
