# Generated by Django 3.2.7 on 2022-12-22 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_camion_tipo_trabajo_trabajo_trabajo_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name=' Nombres ')),
                ('Telefono', models.CharField(max_length=150, unique=True, verbose_name=' Telefonos ')),
                ('Ruc', models.CharField(max_length=150, unique=True, verbose_name=' Ruc ')),
                ('email', models.CharField(max_length=150, unique=True, verbose_name=' email ')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cliente', models.CharField(max_length=150, unique=True, verbose_name=' clientes ')),
                ('camion_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.camion')),
                ('grano_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.grano')),
            ],
            options={
                'verbose_name': 'Entregas',
                'verbose_name_plural': 'Entregas',
                'db_table': 'Entregas',
                'ordering': ['id'],
            },
        ),
    ]
