# Generated by Django 3.2.7 on 2022-12-22 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_cliente_entregas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregas',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cliente'),
        ),
    ]
