# Generated by Django 3.2.7 on 2023-01-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_camion_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='chapa',
            field=models.CharField(max_length=4, unique=True, verbose_name=' Chapas '),
        ),
        migrations.AlterField(
            model_name='camion',
            name='nombre_conductor',
            field=models.CharField(max_length=40, verbose_name=' Nombres '),
        ),
    ]
