# Generated by Django 3.2.7 on 2023-01-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20230103_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='cedula',
            field=models.CharField(max_length=7, unique=True, verbose_name=' Cedula '),
        ),
        migrations.AlterField(
            model_name='camion',
            name='chapa',
            field=models.CharField(max_length=7, unique=True, verbose_name=' Chapas '),
        ),
    ]
