# Generated by Django 3.2.7 on 2023-01-04 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20230103_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camion',
            old_name='nombre_conductor',
            new_name='nombre',
        ),
    ]
