# Generated by Django 3.2.7 on 2023-01-04 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_rename_nombre_conductor_camion_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajo',
            old_name='parcela',
            new_name='nombre',
        ),
    ]
