# Generated by Django 3.2.7 on 2023-01-05 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_parcela_trabajo_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grano',
            old_name='kilogramos',
            new_name='stock',
        ),
    ]
