# Generated by Django 3.2.7 on 2023-01-05 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_rename_kilogramos_grano_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grano',
            old_name='stock',
            new_name='kilogramos',
        ),
    ]
