# Generated by Django 3.2.7 on 2023-01-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_rename_kilogramos_grano_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregas',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grano',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
