# Generated by Django 3.2.7 on 2023-01-05 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_entregas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregas',
            name='camion_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.camion'),
        ),
        migrations.AlterField(
            model_name='entregas',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='entregas',
            name='grano_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.grano'),
        ),
        migrations.AlterField(
            model_name='grano',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
