# Generated by Django 3.2.7 on 2023-01-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20230105_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grano',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
