# Generated by Django 3.2.7 on 2023-01-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_grano_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregas',
            name='grano_id',
        ),
        migrations.AddField(
            model_name='entregas',
            name='grano_id',
            field=models.ManyToManyField(null=True, to='core.Grano'),
        ),
    ]
