# Generated by Django 3.2.7 on 2023-01-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20230106_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
