# Generated by Django 3.2.7 on 2023-01-06 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_entregas_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregas',
            name='grano_id',
        ),
        migrations.AddField(
            model_name='entregas',
            name='grano_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.grano'),
        ),
    ]
