# Generated by Django 3.2.7 on 2023-01-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20230106_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregas',
            name='grano_id',
        ),
        migrations.AddField(
            model_name='entregas',
            name='grano_id',
            field=models.ManyToManyField(null=True, to='core.Grano'),
        ),
        migrations.AlterField(
            model_name='entregas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
