# Generated by Django 3.2.7 on 2023-01-10 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_rename_telefono_cliente_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Ruc',
            new_name='ruc',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='Ruc',
            new_name='ruc',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='Telefono',
            new_name='telefono',
        ),
    ]
