# Generated by Django 3.2.7 on 2023-01-11 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20230109_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grano',
            name='procedencia',
        ),
    ]
