# Generated by Django 3.2.7 on 2023-01-11 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_grano_procedencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='grano',
            name='Procedencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.proveedor'),
            preserve_default=False,
        ),
    ]
