# Generated by Django 3.2.7 on 2023-01-12 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_grano_procedencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quimico',
            name='procedencia',
        ),
    ]
