# Generated by Django 3.2.7 on 2023-01-12 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_quimico_procedencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='quimico',
            name='procedencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.proveedor'),
            preserve_default=False,
        ),
    ]
