# Generated by Django 4.1 on 2023-01-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_quimico_procedencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelas',
            name='trabajos',
        ),
    ]
