# Generated by Django 4.1 on 2023-01-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_produccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregas',
            name='fecha',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='fecha',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
