# Generated by Django 4.1 on 2023-01-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_entregas_fecha_produccion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregas',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateField(),
        ),
    ]
