# Generated by Django 3.2.7 on 2023-01-25 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_entregas_fecha_alter_produccion_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajo',
            old_name='nombre',
            new_name='parcela',
        ),
    ]
