# Generated by Django 3.2.7 on 2023-01-25 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_rename_nombre_trabajo_parcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='fecha',
            field=models.DateField(default='2023-01-02'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.type'),
        ),
        migrations.AlterField(
            model_name='grano',
            name='Procedencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor'),
        ),
        migrations.AlterField(
            model_name='quimico',
            name='procedencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='parcela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.parcelas'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipo_trabajo'),
        ),
        migrations.AlterField(
            model_name='trabajo_stock',
            name='quimico_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.quimico'),
        ),
        migrations.AlterField(
            model_name='trabajo_stock',
            name='trabajo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.trabajo'),
        ),
    ]
