# Generated by Django 3.2.7 on 2023-01-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_trabajo_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajo_stock',
            old_name='gasto',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='trabajo_stock',
            old_name='quimico_id',
            new_name='quimico',
        ),
        migrations.RenameField(
            model_name='trabajo_stock',
            old_name='trabajo_id',
            new_name='trabajo',
        ),
        migrations.AddField(
            model_name='trabajo_stock',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
