# Generated by Django 3.2.7 on 2023-01-27 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20230127_1942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trabajo_stock',
            new_name='Det_Trabajo',
        ),
    ]
