# Generated by Django 3.2.7 on 2023-01-27 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_rename_trabajo_stock_det_trabajo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quimico',
            options={},
        ),
        migrations.AlterModelTable(
            name='quimico',
            table=None,
        ),
    ]
