# Generated by Django 3.2.7 on 2023-01-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20230127_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='quimico',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
