# Generated by Django 3.2.7 on 2023-01-29 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_quimico_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quimico',
            old_name='nombre',
            new_name='name',
        ),
    ]
