# Generated by Django 3.2.7 on 2023-01-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_rename_nombre_quimico_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='det_trabajo',
            name='trabajo',
        ),
    ]
