# Generated by Django 3.2.7 on 2023-01-29 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_remove_det_trabajo_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='det_trabajo',
            name='trabajo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.trabajo'),
        ),
    ]
