# Generated by Django 3.2.7 on 2023-02-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20230129_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='descripcion',
            field=models.CharField(max_length=50, verbose_name=' descripcion '),
        ),
    ]
