# Generated by Django 3.2.7 on 2023-02-02 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_trabajo_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='det_trabajo',
            options={'ordering': ['id'], 'verbose_name': 'Trabajo Detalle', 'verbose_name_plural': 'Trabajo Detalle'},
        ),
        migrations.AlterModelTable(
            name='det_trabajo',
            table='Trabajo Detalle',
        ),
    ]
