# Generated by Django 3.2.7 on 2023-02-02 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20230202_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregas',
            name='grano_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.quimico'),
        ),
        migrations.AlterField(
            model_name='quimico',
            name='ingrediente',
            field=models.CharField(max_length=10, unique=True, verbose_name=' Descripcion '),
        ),
    ]
